@Api_HostAddress = http://0.0.0.0:5260

### Create session
POST {{Api_HostAddress}}/api/session
Accept: application/json
Content-Type: application/json

{
    "email": "alice.alright@test.com",
    "password": "P@$$w0rd"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### Refresh session
POST {{Api_HostAddress}}/api/session/refresh
Accept: application/json
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### Revoke session
DELETE {{Api_HostAddress}}/api/session
Accept: application/json
Authorization: Bearer {{accessToken}}

### Request password reset
POST {{Api_HostAddress}}/api/identity/password-reset/request
Accept: application/json
Content-Type: application/json

{
    "email": "alice.alright@test.com"
}

### Confirm password reset
POST {{Api_HostAddress}}/api/identity/password-reset/confirm
Accept: application/json
Content-Type: application/json

{
    "resetToken": "reset-token-from-email",
    "password": "P@$$w0rd"
}

###
