@Api_HostAddress = http://0.0.0.0:5260
client.global.set("accountUid", "00000000-0000-0000-0000-000000000000");

### Request password reset
POST {{Api_HostAddress}}/api/identity/password-reset/request
Accept: application/json
Content-Type: application/json

{
    "email": "alice.alright@test.com"
}

### Confirm password reset
POST {{Api_HostAddress}}/api/identity/password-reset/confirm
Accept: application/json
Content-Type: application/json

{
    "token": "0123456789abcdef",
    "password": "P@$$w0rd"
}

###
